teleop_twist_joy_node:
  ros__parameters:
      axis_linear:
        x: 1
      scale_linear:
        x: 0.5 # maximum meters per second
      
      axis_angular:
        yaw: 0
      scale_angular:
        yaw: 1.0 # maximum radians per second

      enable_button: 4

joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0
